#!/bin/python
import random

notes = ["./integration",
"./integration/itemCats.md",
"./integration/serviceProfile.md",
"./integration/itemTypes.md",
"./integration/documentTypes.md",
"./integration/docStructure.md",
"./integration/main.md",
"./managing",
"./managing/main.md",
"./outbound",
"./outbound/main.md",
"./vas.md",
"./DiscoveringExtendedWarhouseManagement",
"./DiscoveringExtendedWarhouseManagement/ProcessingAGoodsReciept.md",
"./overview",
"./overview/wareouseProduct.md",
"./overview/quant.md",
"./overview/deploymentOpt.md",
"./overview/les.md",
"./overview/binCord.md",
"./overview/ErpEwmDifferences.md",
"./overview/storageTypeRole.md",
"./overview/masterData.md",
"./overview/outlineMasterData.md",
"./overview/ewm.md",
"./overview/stagingArea.md",
"./overview/warehouseTasks.md",
"./documentCats.md",
"./warehouseManagementMonitor.md",
"./optimizationOR",
"./optimizationOR/main.md",
"./putawayProcess.md",
"./DiscoveringExtendedWarehouseManagement",
"./DiscoveringExtendedWarehouseManagement/IdentifyingTheNeedForWarehouseManagementSolution.md",
"./outline",
"./outline/packingSpec.md",
"./putaway",
"./putaway/strategies.md",
"./putaway/main.md",
"./udemyNotes.md",
"./pick_random.py",
"./acronyms.md",
"./warehouseProcessTypes.md",
"./masterData",
"./masterData/workCenter.md",
"./masterData/dataTransfer.md",
"./processes",
"./processes/outline.md",
"./processes/purchaseOrder.md",
"./processes/main.md",
"./processes/ppf.md",
"./mobile",
"./mobile/main.md",
"./additionalFunctions",
"./additionalFunctions/batch.md",
"./additionalFunctions/serialNumber.md",
"./additionalFunctions/qualityInspection.md",
"./additionalFunctions/LayoutOrientatedSC.md",
"./additionalFunctions/main.md",
"./additionalFunctions/processOrientedStorageControl.md",
"./kit.md",
"./warehouseOrg"
"./warehouseOrg/main.md",
"./orgData.md"
]

r = random.choice(notes)
while not r.endswith(".md"):
    r = random.choice(notes)
print(r)
